version: "{build}"

os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

platform:
  - x64
  - x86

install:
  - ps: Install-Product node 10 $env:platform
  - cmd: npm install
  - cmd: npm run dist

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
    release: Wey $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '(placeholder)'
    auth_token:
      secure: NgSrGzkhyMVTkMlZI+6sp6QOyzwPzHrwsnDgOlNZcYEGjIh9ucGHPNzub34DunFx
    artifact: /.*\.zip/
    draft: true
    force_update: true
    prerelease: false
    on:
      appveyor_repo_tag: true

# disable build and test pahses
build: off
test: off
